#!/bin/sh
# prerm script for ldm-themes
#
# see: dh_installdeb(1)

set -e

case "$1" in
    remove|deconfigure|failed-upgrade)

        update-alternatives --remove x-cursor-theme /usr/share/icons/Bibata-Modern-Classic/cursor.theme
        update-alternatives --remove x-cursor-theme /usr/share/icons/Bibata-Modern-Ice/cursor.theme
        update-alternatives --remove x-cursor-theme /usr/share/icons/Bibata-Original-Classic/cursor.theme
        update-alternatives --remove x-cursor-theme /usr/share/icons/Bibata-Original-Ice/cursor.theme
        update-alternatives --remove x-cursor-theme /usr/share/icons/GoogleDot-Black/cursor.theme
        update-alternatives --remove x-cursor-theme /usr/share/icons/GoogleDot-White/cursor.theme
        update-alternatives --remove x-cursor-theme /usr/share/icons/XCursor-Pro-Dark/cursor.theme
        update-alternatives --remove x-cursor-theme /usr/share/icons/XCursor-Pro-Light/cursor.theme

    ;;

    upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
